### ISSUE TITLE
Project not Building

### ISSUE THREAD

**Issue by ESIDEM** [googlesamples/android-instant-apps#4] opened 2017-05-20 11:08 UTC
Error:failed parsing overlays.
Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process C:\Android\Sdk\build-tools\26.0.0-rc2\aapt2.exe with arguments {link -I C:\Android\Sdk\platforms\android-25\android.jar --manifest C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\manifests\full\debug\AndroidManifest.xml -R @C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\incremental\processDebugResources\aapt-temp\aapt-resources-list.txt --auto-add-overlay --java C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\generated\source\r\debug -o C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\res\debug\resources-debug.ap_ --custom-package com.example.android.unsplash -0 apk --output-text-symbols C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\symbols\debug\R.txt --no-version-vectors}
Error:com.android.ide.common.process.ProcessException: Error while executing process C:\Android\Sdk\build-tools\26.0.0-rc2\aapt2.exe with arguments {link -I C:\Android\Sdk\platforms\android-25\android.jar --manifest C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\manifests\full\debug\AndroidManifest.xml -R @C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\incremental\processDebugResources\aapt-temp\aapt-resources-list.txt --auto-add-overlay --java C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\generated\source\r\debug -o C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\res\debug\resources-debug.ap_ --custom-package com.example.android.unsplash -0 apk --output-text-symbols C:\Users\ESIDEM jnr\Desktop\android-instant-apps-master\multi-feature-module\installed\build\intermediates\symbols\debug\R.txt --no-version-vectors}
Error:org.gradle.process.internal.ExecException: Process 'command 'C:\Android\Sdk\build-tools\26.0.0-rc2\aapt2.exe'' finished with non-zero exit value 1
Error:Execution failed for task ':installed:processDebugResources'.
> Failed to execute aapt
![screenshot 111](https://cloud.githubusercontent.com/assets/22343622/26275288/db276360-3d54-11e7-8647-7cf5c64ca6d4.png)

**Comment by keyboardsurfer** [comment] 2017-05-23 11:28
May be a duplicate of #2. Please see if the given workaround applies to you.

**Closed as completed** 2017-06-22 12:14 UTC
