### ISSUE TITLE
Instant app doesn't build: Invalid dimen

### ISSUE THREAD

**Issue by Dawars** [googlesamples/android-instant-apps#2] opened 2017-05-18 10:47 UTC
The assembleDebug task fails with the following error message when I try to run the _instant_ module, the _installed_ module starts fine.
I tried creating a new project as well as using the sample project here but both fail.

![instant_app](https://cloud.githubusercontent.com/assets/1162980/26198815/d2ab1ecc-3bc7-11e7-974b-5d8badcc8b17.png)

https://pastebin.com/r1LfsLTR

I have Ubuntu 16.04 and just installed Android Studio 3 with the latest tools.

**Comment by keyboardsurfer** [comment] 2017-05-18 16:52
I couldn't reproduce the issue on either of the projects. Could you try `./gradlew clean assemble` on the command line and see if the problem persists?

**Comment by Dawars** [comment] 2017-05-18 18:28
I get the same error message. I tried on 2 separate Ubuntu machines.

**Comment by adamkoch** [comment] 2017-05-18 18:33
Are you on Ubuntu as well? Can you send the actual dimen value inside the merged values.xml?

**Comment by Dawars** [comment] 2017-05-18 18:37
Here:
https://pastebin.com/vt0WSJVv

**Comment by Dawars** [comment] 2017-05-18 18:42
Here is the whole values.xml: https://pastebin.com/vt0WSJVv

line 244:`<item format="float" name="abc_disabled_alpha_material_dark" type="dimen">0.30</item>`
line 282:`<item format="float" name="disabled_alpha_material_dark" type="dimen">0.30</item>`
line 285:`<item format="float" name="highlight_alpha_material_colored" type="dimen">0.26</item>`
etc

It's the lines in that format having no unit.

These are fine:

`    <item name="abc_dialog_fixed_height_minor" type="dimen">100%</item>`
`<item name="abc_dialog_fixed_width_major" type="dimen">320dp</item>
`

**Comment by kelvinc1024** [comment] 2017-05-19 05:23
![screenshot from 2017-05-19 12-20-40](https://cloud.githubusercontent.com/assets/13277668/26234274/b43e8be2-3c8d-11e7-82f8-7d49a48320f6.png)
Same here, also tried in ubuntu 16.04 Android Studio 3.0 with latest tools
both modules are failed

**Comment by friedger** [comment] 2017-05-19 10:07
Same for the codelab

**Comment by keyboardsurfer** [comment] 2017-05-19 10:30
Thanks for your reports. We're looking into the source of the issue.

**Comment by saturov** [comment] 2017-05-22 06:08
Same here on Ubuntu 16.04. It started to reproduce since I moved to Android Studio 3.0 from 2.3 with my Instant App project.

**Comment by keyboardsurfer** [comment] 2017-05-23 11:27
The workaround is to switch your development machine to a locale which uses "." as a decimal mark.
To track the fix of this issue star [this issue from the Google issuetracker](https://issuetracker.google.com/issues/64962882).

**Comment by Dawars** [comment] 2017-05-23 11:50
It has to do with the regional formats, not the local. 
It can be changed the following way:
![image](https://cloud.githubusercontent.com/assets/1162980/26352952/42452cd8-3fbe-11e7-99b8-f2b5ccc47959.png)

**Comment by LeadManPL** [comment] 2017-08-31 00:17
AS 3.0 Beta 2 still has this issue. Changing regional settings is rather workaround, than a solution...

**Comment by keyboardsurfer** [comment] 2017-08-31 08:15
We are aware of this issue and are working on a solution.
There's a link to a tracked issue in [my comment above](https://github.com/googlesamples/android-instant-apps/issues/2#issuecomment-303369358).

**Comment by ktiusks** [comment] 2017-09-14 15:29
Hello, 
How is it resolved for debian 9? Thanks.

**Comment by keyboardsurfer** [comment] 2017-09-18 11:15
Hi @ktiusks, have you tried the solutions provided both in this thread and in the issuetracker link above?

**Comment by LeadManPL** [comment] 2017-09-18 11:34
Just a notification,
Android Studio 3.0 Beta 6 still has this issue.
Changing regional settings workaround, still saves the day ;P

**Comment by jcuypers** [comment] 2017-10-02 21:06
Tying android studio 3.0.0 beta 6
for some reason it doesnt seem to work for me.  still invalid dimen error for all decimal 0.xx values.  current locale is correctly set:  
```
`jcuypers@nostradamus:/usr/local/android-studio-preview/bin$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```
`

**Comment by LeadManPL** [comment] 2017-10-03 08:01
@jcuypers : try out this one:  https://stackoverflow.com/a/44304075

**Comment by jcuypers** [comment] 2017-10-23 19:19
sorry for the late reply.  It seems that Beta 7 has solved the issue.  I dont know whether this has worked because of my previous changes already or Its solely because of the update.   If you have issues like this I would recommended to upgrade to the latest and to tray again.  thanks

**Comment by keyboardsurfer** [comment] 2017-10-24 16:08
Closing this issue. Please continue discussion on the [Google Issue Tracker](https://issuetracker.google.com/issues/64962882) if necessary.

**Closed as completed by keyboardsurfer** 2017-10-24 16:08 UTC
