### ISSUE TITLE
Reading bundle timed out

### ISSUE THREAD

**Issue by iRuoBin** [googlesamples/android-instant-apps#42] opened 2018-01-25 08:47 UTC
IDE: Android Studio 3.0.1  Device: Samsung C5 Pro  (Google Account Signin, InstantApp turn On)
Log: 01/25 16:43:00: Launching instant
Side loading instant app.
Side loading instant app.
Side loading instant app.
Side loading instant app.
Side loading instant app failed: Reading bundle timed out.
Error while Uploading and registering Instant App

**Comment by keyboardsurfer** [comment] 2018-05-04 13:34
Duplicate of #32

**Closed as completed by keyboardsurfer** 2018-05-04 13:34 UTC
